spring:
  banner:
    charset: UTF-8
  application:
    name: @project.artifactId@
    version: @project.version@
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_service
    username: postgres
    password: h@sib2211
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    time-zone: Asia/Dhaka
  mail:
    host: smtp.hostinger.com
    port: 587
    username: hasibul.hoque@businessaccelerate.com.bd
    password: H@sib300814
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
